[package]
name = "backup"
version = "0.0.1"
edition = "2018"
publish = false

[[test]]
name = "integrations"
path = "tests/integrations/mod.rs"

[features]
default = ["protobuf-codec", "test-engines-rocksdb"]
protobuf-codec = [
  "engine_rocks/protobuf-codec",
  "external_storage/protobuf-codec",
  "grpcio/protobuf-codec",
  "keys/protobuf-codec",
  "kvproto/protobuf-codec",
  "raft/protobuf-codec",
  "raftstore/protobuf-codec",
  "tikv/protobuf-codec",
  "txn_types/protobuf-codec",
]
prost-codec = [
  "engine_rocks/prost-codec",
  "external_storage/prost-codec",
  "grpcio/prost-codec",
  "keys/prost-codec",
  "kvproto/prost-codec",
  "raft/prost-codec",
  "raftstore/prost-codec",
  "tikv/prost-codec",
  "txn_types/prost-codec",
]
tcmalloc = ["tikv/tcmalloc"]
jemalloc = ["tikv/jemalloc"]
mimalloc = ["tikv/mimalloc"]
portable = ["tikv/portable"]
sse = ["tikv/sse"]
mem-profiling = ["tikv/mem-profiling"]
failpoints = ["tikv/failpoints"]
test-engines-rocksdb = ["tikv/test-engines-rocksdb"]
test-engines-panic = ["tikv/test-engines-panic"]

[dependencies]
concurrency_manager = { path = "../concurrency_manager" }
configuration = { path = "../configuration" }
crc64fast = "0.1"
engine_rocks = { path = "../engine_rocks" }
engine_traits = { path = "../engine_traits" }
error_code = { path = "../error_code" }
external_storage = { path = "../external_storage" }
failure = "0.1"
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
grpcio = { version = "0.6", default-features = false, features = ["openssl-vendored"] }
hex = "0.4"
keys = { path = "../keys" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
lazy_static = "1.3"
pd_client = { path = "../pd_client" }
prometheus = { version = "0.10", default-features = false, features = ["nightly"] }
raft = { version = "0.6.0-alpha", default-features = false }
raftstore = { path = "../raftstore" }
security = { path = "../security" }
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tidb_query_common = { path = "../tidb_query_common" }
tikv = { path = "../../", default-features = false }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
txn_types = { path = "../txn_types" }
yatp = { git = "https://github.com/tikv/yatp.git", branch = "master" }

[dev-dependencies]
futures-executor = "0.3"
rand = "0.7"
tempfile = "3.0"
test_util = { path = "../test_util" }
test_raftstore = { path = "../test_raftstore" }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
