[package]
name = "engine_test"
version = "0.0.1"
description = "A single engine that masquerades as all other engines, for testing"
edition = "2018"
publish = false

[features]
default = []
test-engine-kv-panic = []
test-engine-kv-rocksdb = []
test-engine-raft-panic = []
test-engine-raft-rocksdb = []


[dependencies]
engine_traits = { path = "../engine_traits" }
engine_rocks = { path = "../engine_rocks" }
engine_panic = { path = "../engine_panic" }
tempfile = "3.0"
tikv_alloc = { path = "../tikv_alloc" }
# FIXME: Remove this dep from the engine_traits interface
tikv_util = { path = "../tikv_util" }
