[package]
name = "test_util"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
encryption = { path = "../encryption" }
fail = "0.4"
grpcio = { version = "0.6", default-features = false, features = ["openssl-vendored"] }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
rand = "0.7"
rand_isaac = "0.2"
security = { path = "../security" }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tempfile = "3.0"
tikv_util = { path = "../tikv_util" }
time = "0.1"
