[package]
name = "pd_client"
version = "0.1.0"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "grpcio/protobuf-codec",
  "kvproto/protobuf-codec",
  "txn_types/protobuf-codec",
]
prost-codec = [
  "grpcio/prost-codec",
  "kvproto/prost-codec",
  "txn_types/prost-codec",
]
failpoints = ["fail/failpoints"]

[dependencies]
error_code = { path = "../error_code" }
futures = "0.3"
grpcio = { version = "0.6", default-features = false, features = ["openssl-vendored"] }
hex = "0.4"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
lazy_static = "1.3"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
prometheus = { version = "0.10", features = ["nightly"] }
quick-error = "1.2.3"
security = { path = "../security" }
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
tokio-timer = "0.2"
txn_types = { path = "../txn_types" }
semver = "0.10"
fail = "0.4"
