[package]
name = "sst_importer"
version = "0.1.0"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "external_storage/protobuf-codec",
  "grpcio/protobuf-codec",
  "keys/protobuf-codec",
  "kvproto/protobuf-codec",
  "txn_types/protobuf-codec",
]
prost-codec = [
  "external_storage/prost-codec",
  "grpcio/prost-codec",
  "keys/prost-codec",
  "kvproto/prost-codec",
  "txn_types/prost-codec",
]

[dependencies]
crc32fast = "1.2"
encryption = { path = "../encryption" }
engine_rocks = { path = "../engine_rocks" }
engine_traits = { path = "../engine_traits" }
error_code = { path = "../error_code" }
external_storage = { path = "../external_storage" }
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
grpcio = { version = "0.6", default-features = false, features = ["openssl-vendored"] }
keys = { path = "../keys" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
lazy_static = "1.3"
log_wrappers = { path = "../log_wrappers" }
prometheus = { version = "0.10", default-features = false }
quick-error = "1.2.3"
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
tokio = { version = "0.2.13", features = ["time", "rt-threaded", "macros"] }
txn_types = { path = "../txn_types" }
uuid = { version = "0.8.1", features = ["serde", "v4"] }

[dev-dependencies]
engine_rocks = { path = "../engine_rocks" }
tempfile = "3.0"
test_util = { path = "../test_util" }
test_sst_importer = { path = "../test_sst_importer" }
