[package]
name = "tidb_query_executors"
version = "0.0.1"
edition = "2018"
publish = false
description = "A vector query engine to run TiDB pushed down executors"

[dependencies]
protobuf = "2.8"
codec = { path = "../codec" }
fail = "0.4"
hex = "0.4"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
match_template = { path = "../match_template" }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
smallvec = "1.4"
tidb_query_datatype = { path = "../tidb_query_datatype" }
tidb_query_common = { path = "../tidb_query_common" }
tidb_query_expr = { path = "../tidb_query_expr" }
tidb_query_aggr = { path = "../tidb_query_aggr" }
tikv_util = { path = "../tikv_util" }
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
yatp = { git = "https://github.com/tikv/yatp.git", branch = "master" }

[dev-dependencies]
failure = "0.1"
tipb_helper = { path = "../tipb_helper" }
tidb_query_codegen = { path = "../tidb_query_codegen" }
