[package]
name = "test_pd"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "grpcio/protobuf-codec",
  "kvproto/protobuf-codec",
  "pd_client/protobuf-codec",
]
prost-codec = [
  "grpcio/prost-codec",
  "kvproto/prost-codec",
  "pd_client/prost-codec",
]

[dependencies]
fail = "0.4"
futures = "0.3"
grpcio = { version = "0.6", default-features = false, features = ["openssl-vendored"] }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
pd_client = { path = "../pd_client" }
security = { path = "../security" }
tikv_util = { path = "../tikv_util" }
