[package]
name = "tidb_query_common"
version = "0.0.1"
edition = "2018"
publish = false
description = "Common utility of a query engine to run TiDB pushed down executors"

[dependencies]
hex = "0.4"
time = "0.1"
failure = "0.1"
derive_more = "0.99.3"
error_code = { path = "../error_code" }
tikv_util = { path = "../tikv_util" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
prometheus = { version = "0.10", features = ["nightly"] }
prometheus-static-metric = "0.4"
lazy_static = "1.3"

[dev-dependencies]
byteorder = "1.2"

