[package]
name = "raftstore"
version = "0.0.1"
authors = ["The TiKV Authors"]
license = "Apache-2.0"
edition = "2018"
publish = false

[features]
failpoints = ["fail/failpoints"]
prost-codec = [
  "prost",
  "engine_rocks/prost-codec",
  "into_other/prost-codec",
  "keys/prost-codec",
  "kvproto/prost-codec",
  "raft/prost-codec",
  "pd_client/prost-codec",
  "sst_importer/prost-codec",
  "tidb_query_datatype/prost-codec",
  "txn_types/prost-codec",
]
protobuf-codec = [
  "engine_rocks/protobuf-codec",
  "into_other/protobuf-codec",
  "keys/protobuf-codec",
  "kvproto/protobuf-codec",
  "raft/protobuf-codec",
  "pd_client/protobuf-codec",
  "sst_importer/protobuf-codec",
  "tidb_query_datatype/protobuf-codec",
  "txn_types/protobuf-codec",
]
testexport = []

[dependencies]
batch-system = { path = "../batch-system" }
bitflags = "1.0.1"
byteorder = "1.2"
concurrency_manager = { path = "../concurrency_manager" }
configuration = { path = "../configuration" }
crc32fast = "1.2"
crossbeam = "0.7.2"
engine_rocks = { path = "../engine_rocks" }
encryption = { path = "../encryption" }
engine_traits = { path = "../engine_traits" }
error_code = { path = "../error_code" }
fail = "0.4"
openssl = "0.10"
fs2 = "0.4"
futures = "0.3"
futures-util = { version = "0.3.1", default-features = false, features = ["io"] }
hex = "0.4"
into_other = { path = "../into_other" }
keys = { path = "../keys" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
lazy_static = "1.3"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
log_wrappers = { path = "../log_wrappers" }
pd_client = { path = "../pd_client" }
prometheus = { version = "0.10", features = ["nightly"] }
prometheus-static-metric = "0.4"
prost = { version = "0.6", optional = true }
protobuf = "2.8"
quick-error = "1.2.3"
raft = { version = "0.6.0-alpha", default-features = false }
raft-proto = { version = "0.6.0-alpha", default-features = false }
rand = "0.7.3"
serde = "1.0"
serde_derive = "1.0"
serde_with = "1.4"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
smallvec = "1.4"
sst_importer = { path = "../sst_importer" }
tempfile = "3.0"
tidb_query_datatype = { path = "../tidb_query_datatype" }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
time = "0.1"
tokio = { version = "0.2", features = ["sync", "rt-threaded"] }
txn_types = { path = "../txn_types" }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
yatp = { git = "https://github.com/tikv/yatp.git", branch = "master" }

[dev-dependencies]
engine_test = { path = "../engine_test" }
panic_hook = { path = "../panic_hook" }
test_sst_importer = { path = "../test_sst_importer" }
engine_panic = { path = "../engine_panic" }
