[package]
name = "external_storage"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = ["kvproto/protobuf-codec"]
prost-codec = ["kvproto/prost-codec"]

[dependencies]
bytes = "0.5.3"
futures = "0.3"
futures-executor = "0.3"
futures-io = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
http = "0.2.0"
hyper = "0.13.3"
hyper-tls = "0.4.1"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
lazy_static = "1.3"
prometheus = { version = "0.10", default-features = false, features = ["nightly", "push"] }
rand = "0.7"
rusoto_core = "0.45.0"
rusoto_s3 = "0.45.0"
rusoto_util = { path = "../rusoto_util" }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tame-gcs = { version = "0.8.0", features = ["async-multipart"] }
tame-oauth = "0.4.2"
tikv_alloc = { path = "../tikv_alloc" }
tokio = { version = "0.2.13", features = ["time"] }
url = "2.0"

[dev-dependencies]
structopt = "0.3"
rusoto_mock = "0.45.0"
tempfile = "3.1"
rust-ini = "0.14.0"
matches = "0.1.8"
