[package]
name = "test_raftstore"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "engine_rocks/protobuf-codec",
  "grpcio/protobuf-codec",
  "keys/protobuf-codec",
  "kvproto/protobuf-codec",
  "pd_client/protobuf-codec",
  "raft/protobuf-codec",
  "raftstore/protobuf-codec",
  "tikv/protobuf-codec",
]
prost-codec = [
  "engine_rocks/prost-codec",
  "grpcio/prost-codec",
  "keys/prost-codec",
  "kvproto/prost-codec",
  "pd_client/prost-codec",
  "raft/prost-codec",
  "raftstore/prost-codec",
  "tikv/prost-codec",
]

[dependencies]
crossbeam = "0.7.2"
engine_traits = { path = "../engine_traits" }
engine_rocks = { path = "../engine_rocks" }
futures = "0.3"
grpcio = { version = "0.6", default-features = false, features = ["openssl-vendored"] }
hex = "0.4"
lazy_static = "1.3"
keys = { path = "../keys" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
pd_client = { path = "../pd_client" }
raft = { version = "0.6.0-alpha", default-features = false }
raftstore = { path = "../raftstore" }
rand = "0.7"
security = { path = "../security" }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tempfile = "3.0"
test_util = { path = "../test_util" }
tikv = { path = "../../", default-features = false }
tikv_util = { path = "../tikv_util" }
tokio-timer = "0.2"
txn_types = { path = "../txn_types" }
encryption = { path = "../encryption" }
tokio = { version = "0.2", features = ["rt-threaded"]}
concurrency_manager = { path = "../concurrency_manager" }
fail = "0.4"
