[package]
name = "engine_panic"
version = "0.0.1"
description = "An example TiKV storage engine that does nothing but panic"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "raft/protobuf-codec",
  "kvproto/protobuf-codec",
]
prost-codec = [
  "raft/prost-codec",
  "kvproto/prost-codec",
]

[dependencies]
engine_traits = { path = "../engine_traits" }
tikv_alloc = { path = "../tikv_alloc" }
# FIXME: Remove this dep from the engine_traits interface
tikv_util = { path = "../tikv_util" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
raft = { version = "0.6.0-alpha", default-features = false }
txn_types = { path = "../txn_types" }
